// client/src/lib/recipe-list.svelte
<script>
	import { recipes } from '../stores/recipes';
	import { selectedTags } from '../stores/tags';
	import RecipeRow from './recipe-row.svelte';
	import Fade from './fade.svelte';

	$: if ($selectedTags.length > 0) {
		fetch('/recipes?tags=' + $selectedTags.map((it) => it.id).join(','))
			.then((res) => res.json())
			.then((data) => ($recipes = data));
	}
</script>

<div class="recipe-list">
	{#each $recipes as recipe, i}
		<Fade fromLeft={i % 2 === 0}>
			<div class="recipe-row">
				<RecipeRow {recipe} />
			</div>
		</Fade>
	{/each}
</div>

<style>
	.recipe-list {
		width: 90vw;
		max-width: 900px;
	}

	.recipe-row {
		position: relative;
		margin-bottom: var(--space-xxs);
		box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
		padding: 2rem;
		background-color: white;
		border-radius: 20px;
	}

	/* .recipe-row::after {
		--padding-x: 2rem;

		content: '';
		position: absolute;
		background-color: rgba(0, 0, 0, 0.12);
		height: 1px;
		width: calc(100% - (2 * var(--padding-x)));
		margin-top: 2rem;
		margin-left: var(--padding-x);
	} */
</style>

// client/src/components/RecipeList.vue
<template>
  <v-card class="mx-auto list" v-if="recipes.length > 0">
    <v-list three-lines>
      <div v-for="(recipe, index) in recipes" :key="index">
        <v-list-item :key="index" class="recipe">
          <v-list-item-content>
            <v-list-item-title
              class="title"
              ><h2>
                {{ recipe.title }}
              </h2></v-list-item-title
            >
            <v-list-item-subtitle>
              <v-chip
                v-for="tag in recipe.tags"
                :key="tag"
                class="ma-1"
                :color="colors[tag]"
                >{{ tag }}</v-chip
              >
            </v-list-item-subtitle>
            <v-list-item-action class="time text--lighten">
              {{ recipe.time }}
            </v-list-item-action>
          </v-list-item-content>
        </v-list-item>
        <v-divider class="divider" v-if="index < recipes.length - 1"></v-divider>
      </div>
    </v-list>
  </v-card>
</template>

<script>
export default {
  props: ['recipes', 'colors']
}
</script>

<style scoped>
.list {
  max-width: 800px;
}

.recipe {
  text-align: left;
  padding-left: 50px;
  padding-top: 10px;
}

.title {
  padding-left: 10px;
  padding-bottom: 5px;
}

.time {
  position: absolute;
  top: 15px;
  right: 30px;
  color: #aa00c7;
}

.divider {
  margin: 0px 60px;
}

.chip {
  color: white;
}
</style>
